[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
obsidian = "CsS69vzRAZ4dJXFg68tTnP2ei4XCbYzPENdzQnBWU5Ua"

[programs.devnet]
obsidian = "CsS69vzRAZ4dJXFg68tTnP2ei4XCbYzPENdzQnBWU5Ua"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ARCIUM_CLUSTER_OFFSET=456 node --import tsx node_modules/mocha/bin/mocha.js --timeout 1000000 tests/**/*.ts"

[hooks]
